// Supabase configuration
export const SUPABASE_URL = 'https://sbeeuzzbazykwgshczdl.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiZWV1enpiYXp5a3dnc2hjemRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5NDY0MDcsImV4cCI6MjA0OTUyMjQwN30.jJKg04eMMGWwWrRbofICzQS5daiyHk68bBF8c3PALzo';